stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    metadata_slo:
        duration_slo: 5s
        throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration:

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-data
      endpoint: mc-observability-minio:9000
      access_key: YmQYMMfCAPenMclY1WR1
      secret_key: iXjthlJdpI0fKpz015yMgBKuNPBtSrIvDOED1a3P
      insecure: true

    pool:
      queue_depth: 2000
    wal:
      path: /etc/tempo/wal
