- name: Restart CMP Telegraf service
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: "{{ target_host }}"
    ansible_port: "{{ target_port }}"
    ansible_user: "{{ target_user }}"
    ansible_ssh_private_key_file: "{{ target_sshkey_path }}"
  shell: "systemctl restart cmp-telegraf-{{ site_code }}"

- name: Run CMP Telegraf status command
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_connection: ssh
    ansible_host: "{{ target_host }}"
    ansible_port: "{{ target_port }}"
    ansible_user: "{{ target_user }}"
    ansible_ssh_private_key_file: "{{ target_sshkey_path }}"
  raw: "systemctl status --no-pager cmp-telegraf-{{ site_code }}"
  register: cmp_telegraf_status
  failed_when: cmp_telegraf_status.rc not in [0, 3]

- name: Display CMP Telegraf status
  debug:
    var: cmp_telegraf_status
